services:
  shaymin:
    build:
      context: .
    container_name: shaymin-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: shaymin-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: shaymin
      MONGO_INITDB_ROOT_PASSWORD: Password123_
      MONGO_INITDB_DATABASE: shayminmongodb
    ports:
      - "27111:27017"
    volumes:
      - shaymin-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: shaymin-postgresql
    restart: always
    environment:
      POSTGRES_USER: shaymin
      POSTGRES_PASSWORD: Password123_
      POSTGRES_DB: shayminpostgredb
    ports:
      - "5112:5432"
    volumes:
      - shaymin-postgresql:/data/db/postgresql

volumes:
  shaymin-mongodb:
    driver: local
  shaymin-postgresql:
    driver: local
