
services:
  shaymin:
    build:
      context: .
    container_name: shaymin-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: shaymin-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: shaymin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: shaymindb
    ports:
      - "27111:27017"
    volumes:
      - shaymin-mongodb:/data/db

  postgresql:
    image: postgres:15
    container_name: shaymin-postgresql
    restart: always
    environment:
      POSTGRES_USER: shaymin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: shaymindb
    ports:
      - "5112:5432"
    volumes:
      - shaymin-postgresql:/var/lib/postgresql/data

volumes:
  shaymin-mongodb:
  shaymin-postgresql: