<?php

return [
    // WEAPONS
    [
        'name' => 'Baseball bat',
        'description' => 'Sturdy blunt weapon effective for close combat and self-defense.',
        'category' => 'Weapons',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path'     => 'img/baseballbat.png',
    ],
    [
        'name' => 'Sword',
        'description' => 'Sharp melee weapon ideal for silent and precise attacks.',
        'category' => 'Weapons',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'sword.png',
    ],
    [
        'name' => 'Knife',
        'description' => 'Compact blade suitable for stealth and utility purposes.',
        'category' => 'Weapons',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'knife.png',
    ],
    [
        'name' => 'Axe',
        'description' => 'Heavy-duty weapon capable of chopping through bone and wood.',
        'category' => 'Weapons',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'axe.png',
    ],
    [
        'name' => 'Machete',
        'description' => 'Long blade perfect for slashing through dense areas or enemies.',
        'category' => 'Weapons',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'machete.png',
    ],
    [
        'name' => 'Chainsaw',
        'description' => 'Devastating close-range weapon with high damage output.',
        'category' => 'Weapons',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'chainsaw.png',
    ],
    [
        'name' => 'Gun',
        'description' => 'Reliable ranged weapon suitable for rapid elimination of threats.',
        'category' => 'Weapons',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'gun.png',
    ],
    [
        'name' => 'Bow and Arrow',
        'description' => 'Silent ranged weapon useful for distance attacks and reuse of ammo.',
        'category' => 'Weapons',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'bowandarrow.jpg',
    ],
    [
        'name' => 'Flamethrower',
        'description' => 'Spreads fire across multiple targets, effective for crowd control.',
        'category' => 'Weapons',
        'price' => 50,
        'stock_quantity' => 100,
        'image_path' => 'flamethrower.jpg',
    ],
    [
        'name' => 'Bazooka',
        'description' => 'Powerful explosive weapon designed for maximum destruction.',
        'category' => 'Weapons',
        'price' => 50,
        'stock_quantity' => 100,
        'image_path' => 'bazooka.jpg',
    ],

    // MEDICAL
    [
        'name' => 'Bandaid',
        'description' => 'Adhesive bandage used for covering minor cuts and wounds.',
        'category' => 'Medical',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'bandaid.jpg',
    ],
    [
        'name' => 'Bandage',
        'description' => 'Basic medical supply used to stop bleeding and heal minor wounds.',
        'category' => 'Medical',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'bandage.jpg',
    ],
    [
        'name' => 'Healing Potion',
        'description' => 'Restores health quickly and effectively during critical moments.',
        'category' => 'Medical',
        'price' => 50,
        'stock_quantity' => 100,
        'image_path' => 'healingpotion.jpg',
    ],

    // TOOLS
    [
        'name' => 'Compass',
        'description' => 'Navigation tool used to determine direction and assist in orienteering.',
        'category' => 'Tools',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'compass.jpg',
    ],
    [
        'name' => 'Flashlight',
        'description' => 'Portable light source essential for exploring dark areas.',
        'category' => 'Tools',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'flashlight.jpg',
    ],
    [
        'name' => 'Lighter',
        'description' => 'Compact fire-starting tool useful for survival and cooking.',
        'category' => 'Tools',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'lighter.jpg',
    ],
    [
        'name' => 'Radio',
        'description' => 'Communication device to receive emergency broadcasts and updates.',
        'category' => 'Tools',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'radio.jpg',
    ],
    [
        'name' => 'Binoculars',
        'description' => 'Optical tool for scouting distant areas and spotting threats early.',
        'category' => 'Tools',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'binoculars.jpg',
    ],

    // SUSTENANCE
    [
        'name' => 'Chocolate',
        'description' => 'High-energy food item that boosts morale and provides quick calories.',
        'category' => 'Sustenance',
        'price' => 5,
        'stock_quantity' => 100,
        'image_path' => 'chocolate.jpg',
    ],
    [
        'name' => 'Turon',
        'description' => 'Sweet banana roll snack that offers a quick energy boost.',
        'category' => 'Sustenance',
        'price' => 5,
        'stock_quantity' => 100,
        'image_path' => 'turon.jpg',
    ],
    [
        'name' => 'Chicken',
        'description' => 'Protein-rich meal ideal for restoring stamina.',
        'category' => 'Sustenance',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'chicken.jpg',
    ],
    [
        'name' => 'Rice',
        'description' => 'Carbohydrate staple providing long-lasting energy.',
        'category' => 'Sustenance',
        'price' => 25,
        'stock_quantity' => 100,
        'image_path' => 'rice.jpg',
    ],
    [
        'name' => 'Water',
        'description' => 'Essential for hydration and survival.',
        'category' => 'Sustenance',
        'price' => 10,
        'stock_quantity' => 100,
        'image_path' => 'water.jpg',
    ],

    // BUNDLES
    [
        'name' => 'Beginner\'s Bundle',
        'description' => '3 weapons, 2 medical, 2 sustenance (one food, one water)',
        'category' => 'Sustenance',
        'price' => 150,
        'stock_quantity' => 100,
        'image_path' => 'beginner.jpg',
    ],
    [
        'name' => 'Intermediate Bundle',
        'description' => 'Includes 2 weapons, 2 medical items, 2 tools, and 2 sustenance supplies — perfect for balanced survival.',
        'category' => 'Bundles',
        'price' => 180,
        'stock_quantity' => 100,
        'image_path' => 'intermediate.jpg',
    ],
    [
        'name' => 'Advanced Bundle',
        'description' => 'Loaded with 5 weapons, 2 medical items, 3 tools, and 3 sustenance supplies — ideal for long-term survival.',
        'category' => 'Bundles',
        'price' => 300,
        'stock_quantity' => 100,
        'image_path' => 'advanced.jpg',
    ],
];
